name: "PR & Workflow Checks"

on:
  push:
  pull_request:

permissions:
  statuses: write
  contents: write

jobs:
  title-check:
    name: "PR Title Check"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check PR Title
        uses: step-security/conventional-pr-title-action@v3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
