name: "PR & Workflow Checks"

on:
  push:
  pull_request:

  pull_request_target:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - reopened
      - edited
      - converted_to_draft
      - ready_for_review
      - review_requested
      - review_request_removed
      - locked
      - unlocked
      - synchronize

permissions:
  statuses: write
  contents: write

jobs:

  title-check:
    name: "PR Title Check"
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' }}
    steps:
      - name: Check PR Title
        uses: step-security/conventional-pr-title-action@19fb561b33015fd2184055a05ce5a3bcf2ba3f54
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  assignee-check:
    name: "Assignee Check"
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' }}
    steps:
      - name: Check Assignee
        if: ${{ github.event.pull_request.assignees == null || github.event.pull_request.assignees[0] == null }}
        run: |
          echo "Assignee is not set. Failing the workflow."
          exit 1

  actionlint:
    name: "Lint GitHub Actions Workflows"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download actionlint
        id: get_actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color

  commit-message:
    name: "Commit Message Check"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Semantic PR Title/Commit
        uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            Fix
            Feat
            Chore
            Docs
            Style
            Refactor
            Perf
            Test
            Revert
            CI
            Build
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install gitlint
        run: |
          pip install gitlint

      - name: Run gitlint
        run: |
          gitlint --commits "${{ github.event.pull_request.base.sha }}..HEAD"
