name: "PR & Workflow Checks"

on:
  push:
  pull_request:

permissions:
  statuses: write
  contents: write

jobs:
  title-check:
    name: "PR Title Check"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check PR Title
        uses: step-security/conventional-pr-title-action@v3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  assignee-check:
    name: "Assignee Check"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Check Assignee
        if: ${{ github.event.pull_request.assignees == null || github.event.pull_request.assignees[0] == null }}
        run: |
          echo "Assignee is not set. Failing the workflow."
          exit 1

  commit-message:
    name: "Commit Message Check"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Semantic PR Title/Commit
        uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            Fix
            Feat
            Chore
            Docs
            Style
            Refactor
            Perf
            Test
            Revert
            CI
            Build
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install gitlint
        run: |
          pip install gitlint

      - name: Run gitlint
        run: |
          gitlint --commits "${{ github.event.pull_request.base.sha }}..HEAD"