name: "PR Title Check"

on:
  pull_request:

permissions:
  statuses: write
  contents: write

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: step-security/conventional-pr-title-action@v3.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
