name: Publish to PyPI

on:
  push:
    tags:
    - v0.1.1dev
      # - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install PDM & pdm-backend
        run: pip install pdm pdm-backend

      - name: Install project dependencies
        run: pdm install --prod

      - name: Generate Proto Files
        run: bash ./generate_proto.sh

      - name: Build
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}